// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSrHABq5diJg44XTFXpat_ToFHRamrgPU',
    appId: '1:587019374349:android:e72757367aae2c4c92aa44',
    messagingSenderId: '587019374349',
    projectId: 'dcodaxfood',
    storageBucket: 'dcodaxfood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCzPXWaZ-sGqs8dvp3-_kVjm0B7Qh4F6U',
    appId: '1:587019374349:ios:995b58f51d48a42692aa44',
    messagingSenderId: '587019374349',
    projectId: 'dcodaxfood',
    storageBucket: 'dcodaxfood.appspot.com',
    androidClientId: '587019374349-adilp5v6g6apv67ikg1chji1jptrs0vi.apps.googleusercontent.com',
    iosClientId: '587019374349-ci4vpnt4lfkplhpu54ee2sevhrja54nt.apps.googleusercontent.com',
    iosBundleId: 'app.nerd.vpn',
  );

}